### ISSUE TITLE
Awplus not supported

### ISSUE THREAD

**Issue by morenorobyn** [alliedtelesis/ansible_awplus#38]
Hi whenever i try to connect to my awplus devices using ansible i get the following error

```bash
aw1 | FAILED! => {
    "msg": "network os awplus is not supported"
}
```
Inventory file 
```Bash
[all:vars]
ansible_connection=network_cli

[switches:children]
awplus

[awplus]
aw1 ansible_host=192.168.100.254 

[awplus:vars]
ansible_become=yes
ansible_become_method=enable
ansible_user=username
ansible_password=password
```
Am i using the wrong name in my inventory file or is this project no longer supported?

**Comment by tony-vanderpeet** [comment]
Thanks Mark, you beat me to the reply! Yes, this project is still supported, and we are certainly interested in talking to users of this work, and using your feedback to improve things. I would just add that the released version of this package should also be available as a collection from Ansible Galaxy. https://galaxy.ansible.com/alliedtelesis/awplus

Tony van der Peet
