### ISSUE TITLE
ERROR! Failed to find collection alliedtelesis.awplus:*

### ISSUE THREAD

**Issue by franzlom** [alliedtelesis/ansible_awplus#4]
executing command
    ansible-galaxy collection install alliedtelesis.awplus

Results in
    ERROR! Failed to find collection alliedtelesis.awplus:*

Trying to run this on our ansible instance causes this error.
Also Cannot find this in ansible-galaxy website.
was this removed?

Thanks Franz

**Comment by tony-vanderpeet** [comment]
Franz
I have been tasked with publishing the collection. A miscommunication resulted in this not being done earlier. However, I have just discovered that the process is not as simple as I thought. Hope to have this done by this afternoon (next 4-5 hours). My apologies for the inconvenience.
Tony

**Comment by franzlom** [comment]
Thank you Tony,

Looking  forward to seeing it.

Franz

**Comment by tony-vanderpeet** [comment]
OK, the collection is now there. I was able to install it correctly. I won't close this until you confirm (please raise new issues if there are different problems).

Tony

**Comment by franzlom** [comment]
Thanks Tony,

I managed to install the awplus from ansible-galaxy

thanks for all your help. This is huge!
